version: 2
jobs:
  build:
    working_directory: ~/feedbackfruits-knowledge-graph-broker
    docker:
      - image: node:latest
        environment:
          NODE_ENV: test
          INPUT_TOPIC: update_requests
          OUTPUT_TOPIC: updates
      - image: quay.io/cayleygraph/cayley:v0.7.0-alpha
      # - image: feedbackfruits/feedbackfruits-knowledge-graph:latest
      #   auth:
      #     username: $DOCKERHUB_USER
      #     password: $DOCKERHUB_PASSWORD
      #   environment:
      #     CAYLEY_ENV: test
      - image: wurstmeister/zookeeper:latest
      - image: wurstmeister/kafka:1.0.0
        environment:
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CREATE_TOPICS: "update_requests:1:1,updates:1:1:compact"
    steps:
      - checkout

      - run:
          name: Seed Cayley
          command: |
            curl --fail -H "Content-Type: multipart/form-data" -XPOST -F NQuadFile=@seeds/cayley.nq localhost:64210/api/v1/write/file/nquad

      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn run coverage

      - store_artifacts:
          path: coverage

      - deploy:
          name: Deploy to Heroku
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
              git push git@heroku.com:fbf-knowledge-graph-broker.git $CIRCLE_SHA1:refs/heads/master -f
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push git@heroku.com:staging-fbf-knowledge-graph-b.git $CIRCLE_SHA1:refs/heads/master -f
            fi
