declare const CONCURRENCY: number;
declare const WEB_CONCURRENCY: number;
export { NAME, CAYLEY_ADDRESS, KAFKA_ADDRESS, INPUT_TOPIC, OUTPUT_TOPIC, CONCURRENCY, WEB_CONCURRENCY, KAFKA_PRIVATE_KEY, KAFKA_CERT, KAFKA_CA };
