"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').load({ silent: true });
const { NAME = 'feedbackfruits-knowledge-graph-broker', CAYLEY_ADDRESS = 'http://localhost:64210', KAFKA_ADDRESS = 'tcp://localhost:9092', INPUT_TOPIC = 'update_requests', OUTPUT_TOPIC = 'updates', KAFKA_PRIVATE_KEY, KAFKA_CERT, KAFKA_CA, } = process.env;
exports.NAME = NAME;
exports.CAYLEY_ADDRESS = CAYLEY_ADDRESS;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.INPUT_TOPIC = INPUT_TOPIC;
exports.OUTPUT_TOPIC = OUTPUT_TOPIC;
exports.KAFKA_PRIVATE_KEY = KAFKA_PRIVATE_KEY;
exports.KAFKA_CERT = KAFKA_CERT;
exports.KAFKA_CA = KAFKA_CA;
const CONCURRENCY = parseInt(process.env.CONCURRENCY) || 5;
exports.CONCURRENCY = CONCURRENCY;
