declare const NAME: string, CAYLEY_ADDRESS: string, KAFKA_ADDRESS: string, INPUT_TOPIC: string, OUTPUT_TOPIC: string, KAFKA_PRIVATE_KEY: string, KAFKA_CERT: string, KAFKA_CA: string;
declare const CONCURRENCY: number;
declare const WEB_CONCURRENCY: number;
export { NAME, CAYLEY_ADDRESS, KAFKA_ADDRESS, INPUT_TOPIC, OUTPUT_TOPIC, CONCURRENCY, WEB_CONCURRENCY, KAFKA_PRIVATE_KEY, KAFKA_CERT, KAFKA_CA };
