"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').config();
const { NAME = 'feedbackfruits-knowledge-graph-broker', NODE_ENV = 'development', NEPTUNE_ADDRESS, CAYLEY_ADDRESS = 'http://localhost:64210', KAFKA_ADDRESS = 'tcp://localhost:9092', INPUT_TOPIC = 'update_requests', OUTPUT_TOPIC = 'updates', KAFKA_PRIVATE_KEY, KAFKA_CERT, KAFKA_CA, } = process.env;
exports.NAME = NAME;
exports.NODE_ENV = NODE_ENV;
exports.NEPTUNE_ADDRESS = NEPTUNE_ADDRESS;
exports.CAYLEY_ADDRESS = CAYLEY_ADDRESS;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.INPUT_TOPIC = INPUT_TOPIC;
exports.OUTPUT_TOPIC = OUTPUT_TOPIC;
exports.KAFKA_PRIVATE_KEY = KAFKA_PRIVATE_KEY;
exports.KAFKA_CERT = KAFKA_CERT;
exports.KAFKA_CA = KAFKA_CA;
const CONCURRENCY = parseInt(process.env.CONCURRENCY) || 5;
exports.CONCURRENCY = CONCURRENCY;
const WEB_CONCURRENCY = parseInt(process.env.WEB_CONCURRENCY) || 50;
exports.WEB_CONCURRENCY = WEB_CONCURRENCY;
const GRAPH = 'GRAPH' in process.env ? process.env.GRAPH : `<https://knowledge.express/graph/${NODE_ENV}>`;
exports.GRAPH = GRAPH;
const SEND_UNUPDATED_DOCS = process.env.SEND_UNUPDATED_DOCS === "true" || false;
exports.SEND_UNUPDATED_DOCS = SEND_UNUPDATED_DOCS;
